### ISSUE TITLE
Curious code

### ISSUE THREAD

**Issue by Semigradsky** [johntron/superagent-no-cache#11]
In code you are trying require `ie` module:
```js
var ie
try {
  ie = require('ie')
} catch (e) {
  ie = require('component-ie')
}
```
But this module not in dependencies:
```json
  "dependencies": {
    "component-ie": "^1.0.0"
  },
```
This code is needed? Or maybe just `var ie = require('component-ie')`?

**Comment by Semigradsky** [comment]
I have warning in webpack:
```
WARNING in ./~/superagent-no-cache/index.js
Module not found: Error: Cannot resolve module 'ie' in D:\Dev\git\React\react-ad
min-example\node_modules\superagent-no-cache
 @ ./~/superagent-no-cache/index.js 3:7-20
```

**Comment by johntron** [comment]
@Semigradsky this is common when a module like no-cache supports multiple package managers. In this case, it's npm and Component.io. In Component, the module is called "ie", and the npm package is named "component-ie".

**Comment by Semigradsky** [comment]
Now I understand. Thanks for the explanation!

**Comment by Semigradsky** [comment]
I removed warning by adding alias to webpack config file:
```js
resolve: {
  ...
  alias: {
    ...
    'ie': 'component-ie'
  }
}
```

**Comment by johntron** [comment]
Cool @Semigradsky - that might make a good pull request ;)

**Comment by seb0zz** [comment]
+1

**Comment by laurenskling** [comment]
i am still getting this warning

```WARNING in ./~/superagent-no-cache/index.js
Module not found: Error: Cannot resolve module 'ie' in ..../node_modules/superagent-no-cache
 @ ./~/superagent-no-cache/index.js 3:7-20```
